resource-pack:
  # If enabled will require the use of the resource pack.
  enabled: true
  # The custom font to be used to display the formatting for effects.
  font: "mmobuffs:default"

# Set the settings of the bossbar display here.
bossbar-display:
  enabled: true

  effect-separator: " "

  # Possible colors: white, purple, yellow, green, red, blue, and pink.
  color: 'white'

  # Possible overlays: progress, notched_6, notched_10, notched_12, notched_20.
  overlay: 'progress'

  # Default percentage value of the bossbar. Value must be between [0,1].
  value: 0

on-death:
  # If timed effects should be removed on player death.
  remove-timed-effects: true

  # If permanent effects should be removed on player death.
  remove-permanent-effects: false

# Whether to use a shortened display.
shorten-duration-display: true

config-version: 1