name: MMOBuffs
version: '${project.version}'
main: com.ehhthan.mmobuffs.MMOBuffs
api-version: 1.16
soft-depend: [ MythicLib, PlaceholderAPI ]
authors: [ Ehhthan ]
commands:
  mmobuffs:
    description: Main mmobuffs command.
    aliases: [buff, buffs, mmob, mmobuff]
permissions:
  mmobuffs.reload:
    description: Access to /mmobuffs reload
    default: op